### ISSUE TITLE
Installing on windows leads to `Uncaught ReferenceError: $ is not defined`

### ISSUE THREAD

**Issue by kaustubhhiware** [metakgp/erp-auto-login#15]
Find attached screenshot

I've ran into this error on Chrome 70.0, Windows 10. Could installing something fix this issue?
Is this a windows specific issue or a laptop specific issue? Could be verified by others by installing this on windows.

![image](https://user-images.githubusercontent.com/11318551/47801444-391d1a00-dd54-11e8-9330-587001109830.png)

**Comment by thealphadollar** [comment]
Fixed via #16
