### ISSUE TITLE
[BUG] Extension doesn't work if wrong credentials are entered once 

### ISSUE THREAD

**Issue by thealphadollar** [metakgp/erp-auto-login#27]
As per the screenshot attached, the extension doesn't work if wrong credentials are entered once and then the page is reloaded.

![erp_auto_issue](https://user-images.githubusercontent.com/32812320/91072380-0cd43b00-e657-11ea-9538-0c4503f2dafb.png)

**Comment by sahil-shubham** [comment]
Hey, I would like to work on this issue. Is it available?

**Comment by thealphadollar** [comment]
Thank you very much for your proactiveness Sahil (@sahil-shubham ). Yes, the issue is available to work on, if you face any issue or have doubts please comment as you work forward.
