### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by americast** [metakgp/erp-auto-login#3]
Extend the extension to Mozilla Firefox.

**Comment by thealphadollar** [comment]
Porting to firefox is pretty easy from the existing chrome extension with minor modifications.

References:

- https://hacks.mozilla.org/2015/10/porting-chrome-extensions-to-firefox-with-webextensions/
- https://github.com/thealphadollar/Savitar/commit/d5c7f448bbb73eadea8ad76c92ba8178bb295b9e

**Comment by sahil-shubham** [comment]
Hey @thealphadollar, I would like to work on this issue. Is it available?

**Comment by thealphadollar** [comment]
Yeah, please. I anticipated that same and hence added some more details to the same :star_struck: Please take and solve as you are comfortable.
