### ISSUE TITLE
unexpected behaviour of the credential saved message

### ISSUE THREAD

**Issue by sahil-shubham** [metakgp/erp-auto-login#33]
The issue is with the message **"Your credentials have been saved"**.

### Expected Behaviour 
The message should show up only after entering all the details. 

### Current Behaviour
The message pops up after every keypress.

### Screenshots
![Screenshot from 2020-09-14 01-46-17](https://user-images.githubusercontent.com/60931421/93027674-23edc380-f62c-11ea-904e-2033e38ea24b.png)

**Comment by sahil-shubham** [comment]
@thealphadollar Hey there, I would like to work on this issue.

**Comment by thealphadollar** [comment]
@sahil-shubham This is nice, thanks for bringing it the notice. Do you think we should give some message to let the user know that their inputs get saved as they leave the box and at the same time give a different message when all credentials are saved?

The first thought that came in my mind is below, please feel free to implement your own idea for solving the problem.

We can show "Your credentials have been saved!" when all inputs don't have a value and when all inputs have a value, we can show "Your credentials have been saved, please open ERP!"

**Comment by sahil-shubham** [comment]
> We can show "Your credentials have been saved!" when all inputs don't have a value and when all inputs have a value, we can show "Your credentials have been saved, please open ERP!"

Coincidentally, this was also the first thought that came to my mind. The extension wouldn't show the link to erp till all the credentials have been entered, but it would show something at any keypress. But I would figure out other ways while doing it. Thank you for telling me your views.
