### ISSUE TITLE
Make Security Questions Uneditable 

### ISSUE THREAD

**Issue by ooyeraju** [metakgp/erp-auto-login#36]
Can we make the security questions uneditable, as there's no point of keeping them editable? Also one can just use Tab to answer the next questions.

**Comment by thealphadollar** [comment]
Oh, right! That is a keen observation - thanks a lot Rajnish.

Let's do it 🔥🔥

**Comment by ooyeraju** [comment]
Thanks @thealphadollar  I'll start working on this.
