### ISSUE TITLE
Add toggle switch to extension

### ISSUE THREAD

**Issue by sahil-shubham** [metakgp/erp-auto-login#39]
## Adding a toggle switch to the extension to stop it

As of right now, the extension automatically and almost instantly logins you into erp.  While that is enough for most of the cases but, sometimes one doesn't need to login but rather look something up on the erp login page itself.

### Solutions to the problem

Right now, one has to do any of the following to get around this problem - 

- To reset all the credentials 
- To stop the page from loading before the extension logins
- To use chrome icognito

None of these solutions is perfect. But, **adding a new feature of a toggle button would be easier and better for a user.**

#### Others 

This feature has been partially mentioned in issue #1, as one may try to logout to reach the information on the login page but the extension enters the credentials again. It was also a requested through a [user sugggestion on chrome web store](https://chrome.google.com/webstore/detail/iitkgp-erp-auto-login/gdickphilmdekcbmpjmbnbikchaecbdk)

**Comment by sahil-shubham** [comment]
Hey @thealphadollar , I would like to work on this.

**Comment by thealphadollar** [comment]
Yayyy, please suit yourself as per your comfortability Sahil.

**Comment by thealphadollar** [comment]
@sahil-shubham Are we working on this?

**Comment by sahil-shubham** [comment]
@thealphadollar Yes, I am. I am facing a few problems but should be able to create a PR in a few days. I didn't expect to get this busy when accepting this issue :sweat_smile:

**Comment by thealphadollar** [comment]
No worries Sahil! It's been strange times for all of us, and I'm really thankful it's still on your list. Take your time, I was just curious nothing more.

**Comment by sahil-shubham** [comment]
@thealphadollar Yes, I am on it. I will create a PR this weekend. Thank you for the reminder.

**Comment by sahil-shubham** [comment]
@thealphadollar closing this issue as discussed.
