### ISSUE TITLE
Encrypt and decrypt the variables stored in chrome.store.sync

### ISSUE THREAD

**Issue by athityakumar** [metakgp/erp-auto-login#4]

**Comment by mak1910** [comment]
You could add login using Gmail, and host the backend on heroku. The server should maintain a mapping of Google ID to keys. And the keys returned by the server can be used to encrypt and decrypt the password.

**Comment by athityakumar** [comment]
The issue is actually that, on accessing the `chrome.storage.sync` variables on js console, the user is able to see the exact passwords. So, we should encrypt the form input and store it into chrome storage, and then decrypt it back while using from `login.js` file.

So, we need a js encryptor and decryptor.

**Comment by raivivek** [comment]
I am not sure what the current behavior is; but a user should only be able to set/reset password. That is, the prompt should not contain actual password that can be seen by the user/others.

The workflow could be: Set password -> Password encrypted/saved -> check if it works -> asterisk shown

**Comment by athityakumar** [comment]
@raivivek - Yup, the password as well as security answers are indeed currently shown as astericks in the popup.

![image](https://user-images.githubusercontent.com/17109060/44476902-ce19dd80-a656-11e8-9e88-e8136f19e67d.png)

But when accessed from the JS console, the raw values would be retrievable. So, I was thinking of encrypting/decrypting the password (and security answers) with a salt and then storing into local storage. That way, an ancrypted value will be shown even through the console - but ofcourse, where to store the client-salt mappings then? A server that stores client-salt mappings and provides an end-point to encrypt/decrypt maybe?

**Comment by raivivek** [comment]
Hi @athityakumar -- thanks for following up. Some clarification: when I said show asterisk, I meant show 'literal' asterisks, as in, the raw-values should not be accessible by changing field property (? if possible) or JS console (as you point out). 

I suppose there was another MetaKGP project that was trying to create an authentication backend --- perhaps something like that, or a bitwarden (open source password manager) like service running on our servers. Those will still require you to enter password at least once.

--------------

Actually, now that I think of it, we cannot provide full-proof security and perhaps there's no need for it? Just make it 'not-easy-enough' to spot the details and leave the risks to user.

**Comment by grapheo12** [comment]
Is this still open?
How about we ask the user to provide a key themselves and then we encrypt the userdata using that key. Everytime they attempt to login to erp, they have to provide that key only.

**Comment by thealphadollar** [comment]
Sounds good, please carry on.

**Comment by grapheo12** [comment]
I will use AES then?

**Comment by thealphadollar** [comment]
Again, that is too complex.

Simply use an user given key while storing it. Do not ask the user for
password, the purpose is to make sure that if somebody gets access to
user's system they are unable to get the password by simply going to the
chrome data storage. It is not to make it harder for user.

So, do it as well do for databases in python; simply encrypt it using a key
that given by user / randomly decided.

Look for ways to do it and find an optimal practice.

**Comment by grapheo12** [comment]
That's what I'm asking. I will ask users for a key. Then I'll encrypt the details with AES algo. (User doesn't need to know). The user needs to enter that key everytime he wants to login. (Extra safety so that if the user's PC is compromised, attackers cannot get access to ERP).

**Comment by thealphadollar** [comment]
Okay. Carry forward.

**Comment by athityakumar** [comment]
@grapheo12 - How's it going? Let us know if you need any help! 😄

**Comment by grapheo12** [comment]
Sorry I got a little off track. There are a few issues I'm facing while implementing the encryption in the login page. Actually, my encryption script is not getting called automatically. I think the issue is due to the manifest. I will work on it soon. @athityakumar

**Comment by thealphadollar** [comment]
I believe this issue can be closed. Without repeating the discussion above and the fact that security and usability always go in a trade off. For example, I personally don't want to enter a password when I'm automating the login. So, we will have to provide that way as well. Now, there are complexities to storing passwords/keys in user local storage in anyway. 

On the other hand, I'll present that Git uses plain text file `.gitcredentials` in user's home directory. This is to say that, till we are not storing the credentials of the user, it is their responsibilty to maintain secure access to their own system. If someone has direct access to a person's system, them care much more than just about their ERP password.

Looking forward to knowing everyone's views 🙂
