### ISSUE TITLE
Create A New Logo For The Extension

### ISSUE THREAD

**Issue by thealphadollar** [metakgp/erp-auto-login#40]
The [current logo of the extension](https://github.com/metakgp/erp-auto-login/blob/master/iitkgp.png) is basically the logo of IIT KGP and we are bound to face consequences if the institute gets to know of the same.

We should prepare a new logo, the idea is open to creative submissions. Some guidelines I've in mind are (which are not necessary to be used):

- It represents the ERP and automation.
- May represent metakgp and it's logo in someway.
- Automation can be seen as a key point for the logo.

References:

- Recommended size: https://stackoverflow.com/questions/20424425/recommended-size-of-icon-for-google-chrome-extension
- Icons information in `manifest.json`: https://developer.chrome.com/apps/manifest/icons

**Comment by thealphadollar** [comment]
Hey @ooyeraju Can you please help me with your design learnings here and provide some views as to how we should move forward? :star:

**Comment by ooyeraju** [comment]
Hey, @thealphadollar  I have a very bad idea in my mind. :sweat_smile: 
![image](https://user-images.githubusercontent.com/55256610/93497158-bee8e500-f92d-11ea-9b7b-cc68fe3139f3.png)

It's not the final image, I made it just to convey my idea. (ik it's bad, feel free to criticize it :stuck_out_tongue:  .)  Also if anything else comes in my I'll post it.
