### ISSUE TITLE
Display warning before resetting data

### ISSUE THREAD

**Issue by ooyeraju** [metakgp/erp-auto-login#43]
We should display a warning message to ask confirmation before clearing the data when a user clicks on the reset button.

**Comment by ooyeraju** [comment]
I can work on this?

**Comment by thealphadollar** [comment]
Yes, you can work. No need to ask; by default if you create an issue you are entitled to fix it (if you want).

**Comment by thealphadollar** [comment]
@ooyeraju Are we working on this?

**Comment by ooyeraju** [comment]
Yes, I was busy meeting deadlines this sem 😭. Will work on it ASAP.

**Comment by thealphadollar** [comment]
@ooyeraju Yeah! This sem has been strange and tough :disappointed: . Take your time and do as per your convenience.

**Comment by thealphadollar** [comment]
@ooyeraju  Hey, are there any updates on the issue? I'm planning to release a new version once we have this and #39 closed.

**Comment by ooyeraju** [comment]
Hey, I'm so sorry. 
Actually I had some personal engagements going on. Will so this ASAP.

**Comment by thealphadollar** [comment]
Hey @ooyeraju, @sahil-shubham has already created a PR (#49 )that solves the same. He is facing some issue, you may want to help him there.

**Comment by ooyeraju** [comment]
Yes, sure.

**Comment by thealphadollar** [comment]
fixed via #49
